import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.join(process.cwd(), ".env") });

export default {
  node_env: process.env.NODE_ENV,
  port: process.env.PORT || "5000",
  database_url: process.env.DATABASE_URL,
  bak_url: process.env.APP_URL,
  frontend_url: process.env.FRONTEND_URL,
  bcrypt_salt_rounds: process.env.BCRYPT_SALT_ROUNDS,
  jwt_access_secret: process.env.JWT_ACCESS_SECRET!,
  jwt_refresh_secret: process.env.JWT_REFRESH_SECRET!,
  jwt_access_expires_in: process.env.JWT_ACCESS_EXPIRES_IN!,
  jwt_refresh_expires_in: process.env.JWT_REFRESH_EXPIRES_IN!,
  google_client_id: process.env.GOOGLE_CLIENT_ID!,
  super_admin_frist_name: process.env.SUPER_ADMIN_FRIST_NAME!,
  super_admin_last_name: process.env.SUPER_ADMIN_LAST_NAME!,
  super_admin_name: process.env.SUPER_ADMIN_NAME!,
  super_admin_email: process.env.SUPER_ADMIN_EMAIL!,
  super_admin_password: process.env.SUPER_ADMIN_PASSWORD!,
  tester_admin_first_name: process.env.TESTER_ADMIN_FIRST_NAME!,
  tester_admin_last_name: process.env.TESTER_ADMIN_LAST_NAME!,
  tester_admin_email: process.env.TESTER_ADMIN_EMAIL!,
  tester_admin_password: process.env.TESTER_ADMIN_PASSWORD!,
  tester_finance_admin_first_name: process.env.TESTER_FINANCE_ADMIN_FIRST_NAME!,
  tester_finance_admin_last_name: process.env.TESTER_FINANCE_ADMIN_LAST_NAME!,
  tester_finance_admin_email: process.env.TESTER_FINANCE_ADMIN_EMAIL!,
  tester_finance_admin_password: process.env.TESTER_FINANCE_ADMIN_PASSWORD!,
  tester_registrar_first_name: process.env.TESTER_REGISTRAR_FIRST_NAME!,
  tester_registrar_last_name: process.env.TESTER_REGISTRAR_LAST_NAME!,
  tester_registrar_email: process.env.TESTER_REGISTRAR_EMAIL!,
  tester_registrar_password: process.env.TESTER_REGISTRAR_PASSWORD!,
  tester_instructor_first_name: process.env.TESTER_INSTRUCTOR_FIRST_NAME!,
  tester_instructor_last_name: process.env.TESTER_INSTRUCTOR_LAST_NAME!,
  tester_instructor_email: process.env.TESTER_INSTRUCTOR_EMAIL!,
  tester_instructor_password: process.env.TESTER_INSTRUCTOR_PASSWORD!,
  tester_student_first_name: process.env.TESTER_STUDENT_FIRST_NAME!,
  tester_student_last_name: process.env.TESTER_STUDENT_LAST_NAME!,
  tester_student_email: process.env.TESTER_STUDENT_EMAIL!,
  tester_student_password: process.env.TESTER_STUDENT_PASSWORD!,
  redis_user: process.env.REDIS_USER!,
  redis_password: process.env.REDIS_PASSWORD!,
  redis_host: process.env.REDIS_HOST!,
  redis_port: process.env.REDIS_PORT!,
  smtp_user: process.env.SMTP_USER!,
  smtp_password: process.env.SMTP_PASSWORD!,
  email_sender: process.env.EMAIL_SENDER!,
  cloudinary_cloud_name : process.env.CLOUDINARY_CLOUD_NAME!,
	cloudinary_api_key : process.env.CLOUDINARY_API_KEY!,
	cloudinary_api_secret : process.env.CLOUDINARY_API_SECRET!,
  bkash_base_url: process.env.BKASH_BASE_URL!,
	bkash_username: process.env.BKASH_USERNAME!,
	bkash_password: process.env.BKASH_PASSWORD!,
	bkash_app_key: process.env.BKASH_APP_KEY!,
	bkash_app_secret: process.env.BKASH_APP_SECRET!,
	bkash_callback_url: process.env.BKASH_CALLBACK_URL!,
  stripe_secret_key: process.env.STRIPE_SECRET_KEY!,
  stripe_webhook_secret: process.env.STRIPE_WEBHOOK_SECRET!,
  stripe_success_url: process.env.STRIPE_SUCCESS_URL!,
  stripe_cancel_url: process.env.STRIPE_CANCEL_URL!,
};
